#!/usr/bin/env bash

function run {
  if ! pgrep -f $1 ; then
      $@ &
  fi
  
}

run picom --experimental-backends -b
run polkit-dumb-agent
run dunst
run /home/exwaltz/.config/X11/dwmbar_start
run unclutter --timeout 5 --jitter 2
run mpd
run mpDris2
run fcitx
run sxhkd
run wmname compiz
run searx-run
run birdtray
run volctl
run mpd-discord-rpc
run blueman-applet
run /home/exwaltz/.config/X11/.fehbg
run redshift -l 13:123
# sudo mount UUID=D6E8EC71E8EC5173 ~/Storage/ &

rclone serve webdav --addr exwaltz:8080 /home/exwaltz/Music/ &
rclone serve webdav --vfs-cache-mode full --addr exwaltz:8081 /home/exwaltz/Documents/mounts/Sync/ &
# rclone mount --vfs-cache-mode full PHONE:/ /home/exwaltz/Documents/mounts/PHONE/ &
# run xwinwrap -ov -g 1366x768+0+0 -- mpv -wid WID "/home/exwaltz/Documents/short-background.webm" --no-osc --no-osd-bar --loop-file=inf --player-operation-mode=cplayer --no-audio --panscan=1.0 --no-keepaspect --no-input-default-bindings --hwdec=vaapi
# run xwinwrap -ov -g 1366x768+0+0 -- mpv -wid WID "/home/exwaltz/Videos/hololiveerror-compressed.mp4" --no-osc --no-osd-bar --loop-file=inf --player-operation-mode=cplayer --no-audio --panscan=1.0 --no-keepaspect --no-input-default-bindings --hwdec=vaapi
# run xsettingsd -c ~/.config/xsettingsd/xsettingsd
