#!/bin/bash

file=$(readlink -f "$1")
directory=${file%/*}
base=${file%.*}

cd "$directory"

case $1 in
    *.md) pandoc --filter pandoc-crossref "$file" -o "$base".pdf ;;
    *.tex) pdflatex --output-directory="$directory" "$file" && latexmk -c ;;
    *.py) setid "$TERMINAL" -e python "$file";;
    *.ms) groff -ms -K utf8 -t -U -p -G -e -T pdf "$file"  > "$base".pdf;;
esac
