#!/bin/bash

IFS=:
eachPath=($PATH)
for key in "${eachPath[@]}"; do
    PATHval=$PATHval$(printf "\n%s" $key/* | sed 's/.*\///')
    # Using find instead of ls
    # Slower but much safer
    # PATHval=$(printf "$PATHval\n%s" $(find "$key/" -name "*"))
done
application=$(printf $PATHval | sort -u | tail -n +3 | sed -e 's/fire\>//' -e 's/disco\>//' | dmenu -p "Run:" -hp qutebrowser,inkscape,firefox,brave,gimp,steam,pcmanfm,lodraw,discord,krita,blender,librewolf -i "$@")
${SHELL:-"/bin/sh"} -c "${application}" &
# printf $PATHval | tail -n +2 | sort -u  | dmenu -p "Run:" -i "$@" | ${SHELL:-"/bin/sh"} &
