#!/bin/bash
if printf "%s" "$@"  | grep -q -i "^http\(s\)\?://.*\."; then
    picfname=$(printf "%s%s%s" "$RANDOM" "$(date '+%s')" "$(printf "%s" "$@" | grep -o -i "\.[0-9a-z]\+$" )" )
    curl "$@" -s --output "/tmp/$picfname"
    dragon-drag-and-drop "/tmp/$picfname"
    rm "/tmp/$picfname"
else
    dragon-drag-and-drop "$@"
fi
