#!/bin/bash
if printf "%s" "$@"  | grep -q -i "^http\(s\)\?://.*\."; then
    directory="/tmp/dr-pics"
    mkdir -p "$directory"
    picfname=$(printf "%s%s%s" "$RANDOM" "$(date '+%s')" "$(printf "%s" "$@" | grep -o -i "\.[0-9a-z]\+$" )" )
    curl "$@" -s --output "$directory/$picfname"
    dragon-drag-and-drop "$directory/$picfname"
else
    dragon-drag-and-drop "$@"
fi
