#!/bin/bash
VFile=$1
AFile=$2
OFile=$3

ffmpeg -i "$VFile" -i "$AFile" -deinterlace -pix_fmt yuv420p -c:v libx264 -preset veryfast -tune film -profile:v main -g 25 -crf 26 -x264opts no-scenecut  -c:a aac -ac 2 -ar 44100 -shortest "$OFile"
