#!/bin/bash
ffmpeg -loop 1 -i "$1" -i "$2" -c:v libx264 -tune stillimage -c:a aac -b:a 192k -vf "scale='iw-mod(iw,2)':'ih-mod(ih,2)',format=yuv420p" -map 0:v:0 -map 1:a:0 -shortest -movflags +faststart "$3"
