#!/bin/bash
[ -z "$1" ] && printf "%s\n" "Missing Youtube Link. Use --help for help." && exit 1

player=ffplay

while test $# -gt 0; do
    case $1 in
        --help|-h|help|h)
            printf "%s\n" "${0##*/} - play youtube videos/streams in ffplay/vlc/mpv"
            printf "\t%s\n" "--help      print help"
            printf "\t%s\n" "-v          play in vlc"
            printf "\t%s\n" "-m          play in mpv"
            printf "\t%s\n" "-an         disable audio"
            printf "\t%s\n" "-vn         disable video"
            exit 0
            ;;
        -v)
            player="vlc"
            shift
            ;;
        -m)
            streamInfo=$(curl -s "$2")
            videoTitle=$(printf "%s\n" "$streamInfo" | grep -o '"title":".*\?","len' | sed -e 's/"title"\:"//g' -e 's/","len//g')
            player="mpv"
            shift
            ;;
        -vn)
            player="ffplay"
            noDisplay=" -vn"
            shift
            ;;
        -an)
            player="ffplay"
            noAudio=" -an"
            shift
            ;;
        *)
            [ -z "$1" ] && printf "Missing Link" && exit 1
            youtubeLink=$1
            shift
            [ -z "$1" ] && quality="b" || quality=$1
            shift
            ;;
    esac
done

videoStreamLink=$(yt-dlp -g -f "$quality" "$youtubeLink")

case $player in
    mpv)
        printf "Video Title: %s" "$videoTitle"
        mpv --force-media-title="$videoTitle" "$videoStreamLink"
        ;;
    ffplay)
        ffplay -probesize 20M -i "$videoStreamLink" -framedrop -infbuf -autoexit $noDisplay $noAudio
        ;;
    vlc)
        vlc "$videoStreamLink"
        ;;
esac

