#!/bin/bash
checked=$(printf "%s" "$1" | grep -o '^\-.*')
quality=$2
[ -z $quality ] && quality="best"

if [ ! -z "$checked" ]; then
    quality=$3
    [ -z $quality ] && quality="best"
    cmd=$(youtube-dl -f "$quality" --yes-playlist --get-url "$2")
else
    cmd=$(youtube-dl -f "$quality" --yes-playlist --get-url "$1")
fi
#[ ! -z "$checked" ] && quality=$3 && cmd=$(youtube-dl -f "$quality" --yes-playlist --get-url "$2")  || cmd=$(youtube-dl -f "$quality" --yes-playlist --get-url "$1")
[ -z "$cmd" ] && notify-send -a "ffyt" -t 5000 "Failed" && exit

printf "%s\n" "$quality"

while test $# -gt 0; do
    case $1 in
        --help)
            echo "ffyt - play youtube videos/streams in ffmpeg/vlc"
            echo "--help      print help"
            echo "-f          play in ffplay"
            echo "-v          play in vlc"
            exit 0
            ;;
        -v)
            shift
            vlc "$cmd"
            exit 0
            ;;
        -a)
            ffplay -probesize 20M -i "$cmd" -framedrop -infbuf -autoexit -nodisp
            exit 0
            ;;
        *)
            ffplay -probesize 20M -i "$cmd" -framedrop -infbuf
            exit 0
            ;;
    esac
done
