#!/bin/bash
[ -z "$1" ] && printf "%s\n" "No fonts given" 2>&1 && exit 1
printf "%s\n" "$1" | grep -Eoq '^help|^-h|^h|^--help' && printf "%s\t\t%s\n\n\t%s\n" "finstall " "Installs fonts" "finstall <fontfile>" && exit 0
cp "$@" "$HOME"/.local/share/fonts/
fc-cache -vf 
