#!/bin/bash
# check if the input is valid
# * Must not be empty
[ -z "$1" ] && printf "%s\n" "Missing google drive link" >&2 && exit 1
# * Must have https://drive.google.com at the start and must have "file" or drive after it
grep -viq '^https://drive.google.com/file\|drive' <<< "$1" && printf "%s\n" "Invalid google drive link" && exit 1

# Set array seperator
oldIFS=$IFS
IFS=$'\n'
# Get info from drive
rawDrive=$(curl -L -s "$1")
driveName=$(printf "%s\n" "$rawDrive" | grep -Eoi "title>.+ - " | sed -e 's/^title>//g' -e 's/ - $//g')
if printf '%s\n' "$rawDrive" | grep -ioq 'drive.google.com/file'; then
    fileNames=("$driveName")
    fileLinks=("$(printf "%s\n" "$rawDrive" | grep -Po "id': '.*?'" | sed -e 's/^id'\'': '\''//g' -e 's/'\''$//g' )")
else
    fileNames=( $(printf '%s\n' "$rawDrive" | grep -Poi 'class="Q5txwe" data-tooltip=".*?"' | sed -e 's/^class="Q5txwe" data-tooltip="//g' -e 's/"$//g') )
    fileLinks=( $(printf '%s\n' "$rawDrive" | grep -Poi 'data-id=".+?"' | sed -e 's/^data-id="//g' -e 's/"$//g') )
fi
IFS=$oldIFS

fileNum=${#fileLinks[@]}

# Index drive files
fileSequence=$(seq 0 $(("$fileNum" - 1)))

# Drive Title Header
printf "====================\n\n%s\n\n====================\n\n" "Drive Title: $driveName"

# List all the files in the google drive
for ((FN=0; FN < "$fileNum"; FN++)); do
    printf "%s\n#%-5sFilename: %s\n\tFileID: %s\n%s\n\n" "--------------------" "${FN}:" "${fileNames[$FN]}" "${fileLinks[$FN]}" "--------------------"
done

printf "%s\n" 'To exlcude files (eg: "-10", "-1 -3 -7")'
printf "%s\n" 'To include files (eg: "10", "1 3 7")'
printf "%s\n" 'Put in nothing to include everything'


# Ask the user for files to include or exclude
printf "%s" '==> ' && read -r -a fileOptions
if [ -z "$fileOptions" ]; then
    downloadOption=0
    choosenLink=(${fileLinks[@]})
    choosenName=(${fileNames[@]})
elif printf '%s\n' "$fileOptions" | grep -Eoq '^[0-9]+( [0-9]+)*$'; then
    downloadOption=1
    for elem in ${fileOptions[@]}; do
        [ "$elem" -ge "$fileNum" ] && continue
        choosenLink+=("${fileLinks[$elem]}")
        choosenName+=("${fileNames[$elem]}")
    done
elif printf '%s\n' "$fileOptions" | grep -Eoq '^-[0-9]+( -[0-9]+)*$'; then
    downloadOption=2
    choosenLink=(${fileLinks[@]})
    choosenName=(${fileNames[@]})
    for elem in ${fileOptions[@]}; do
        posElem=$(( elem * -1 ))
        [ $posElem -ge $fileNum ] && continue
        choosenLink=("${choosenLink[@]/${fileLinks[$posElem]}}")
        choosenName=("${choosenName[@]/${fileNames[$posElem]}}")
    done
else
    printf "Invalid Input!\n" 
    exit 1;
fi

for ((item=0; item<${#choosenLink[@]}; item++)); do
    fileLink="https://drive.google.com/uc?id=${choosenLink[$item]}&authuser=0&export=download&confirm=t"
    printf "Filename: %s\n" "${choosenName[$item]}"
    printf "Link: %s\n" "${choosenLink[$item]}"
    #curl -L --fail -o "${choosenName[$item]}" "$fileLink"
    wget -O "${choosenName[$item]}" "$fileLink"
done
