#!/bin/bash
while [ $# -gt 0 ]; do
    case $1 in
        -a|a)
            shift
            git add $1
            shift
            ;;
        -A|A)
            git add -A
            shift
            ;;
        -cm|cm)
            shift
            git commit -m "$1"
            shift
            ;;
        -s|s)
            git status
            shift
            ;;
        -p|p)
            shift
            git push $@
            exit 0
            ;;
        -d|d)
            shift
            git diff $1
            exit 0
            ;;
        --help|-h)
            script_name=${0##*/}
            echo "$script_name - git commands tools"
            echo 
            echo "Options:"
            echo "  -a      add a new file"
            echo "  -A      add all changed files"
            echo "  -cm     commits with message"
            echo "  -s      shows the current status"
            echo "  -p      pushes all changes to github"
            echo "  -d      show file differences"
            echo "  --help  show this help page"
            exit 0
            ;;
    esac
done
