#!/bin/bash
playNpause=$(mpc status | awk '/\[/{print $1}' | grep -iq paused && printf "play" || printf "pause")
title=$(mpc status | awk 'NR==1{print $0}')
choice=$(printf "%s\n%s\n%s\n%s\n%s\n%s" "cancel" "$playNpause" "next" "prev" "clear" "add" | dmenu -p "$title")
case $choice in
    play) mpc play ;;
    pause) mpc pause ;;
    next) mpc next ;;
    prev) mpc prev ;;
    clear) mpc clear ;;
    add) dmenu_playlist ;;
esac
