#!/bin/bash
[ -z "$1" ] && printf "Missing Option\n" 2>&1 && exit 
[ -z "$2" ] && printf "Missing Coin\n" 2>&1 && exit
option=$1
shift
holoCoin=($@)
lenHC=${#holoCoin[@]}

for (( i=0; i<$lenHC; i++)); do
    dataCoin="{\"coin\":\"${holoCoin[$i]}\"}"
    printf "%s\n" "${dataCoin}" "$HOLOSESSION"
    if [ "$option" == "sell" ]; then
        echo "selling"
        curl -X POST -H "Content-Type: application/json" -H "$HOLOSESSION" -d "$dataCoin" -w "\n" https://nasfaq.biz/api/sellCoin/
    elif [ "$option" == "buy" ]; then
        echo "buying"
        curl -X POST  -H "Content-Type: application/json"  -H "$HOLOSESSION" -d "$dataCoin" -w "\n" https://nasfaq.biz/api/buyCoin/
    fi
done
