#!/bin/bash
basename=$(printf "%s\n" "$1" | sed 's/\.[^\/.]*$//')

[ -z "$READER" ] && READER=firefox 

case "$1" in
    *.tex|*.md|*.rmd|*.ms|*.me|*.mom) setsid -f "$READER" "$basename".pdf >/dev/null 2>&1 & ;;
esac
