#!/bin/bash
process=$(pstree -lp | grep -- $1\( | sed "s/.*$1(\([0-9]\+\)).*/\1/")
printf "%s\n" "$process"
# [ -z "$process" ] && printf "Process not found. Quitting...\n" 2>&1 && exit
while [ ! -z "$(pstree -lp | grep -- $1\( | sed "s/.*$1(\([0-9]\+\)).*/\1/")" ]; do
    kill $process
done
$@ &
