#!/bin/bash
[ "$1" == "-h" ] || [ "$1" == "--help" ] || [ "$1" == "help" ] && printf "Usage: resize-image <OutputDir> [Size] <Inputfile>\nResize images and gifs at reasonable quality\n\nSize format: #x# or #\nSize must be integer\n" && exit
[ -z "$1" ] && printf "No Directory Specified\n" 2>&1 && exit
[ "${1: -1}" == "/" ] && outputDIR=${1%?} || outputDIR=$1
shift

aspect=""
extent=""


if printf "%s\n" "$1" | grep -Eoq "[0-9]+x[0-9]+$"; then
    aspect=" -scale $1"
    extent=" -extent $1"
elif printf "%s\n" "$1" | grep -Eoq "^[0-9]+(x)?$"; then 
    aspect=" -scale $1x$1"
    extent=" -extent $1x$1"
else
    printf "Invalid size!\n" 2>&1
    exit 1
fi

shift
[ -z "$1" ] && printf "No Input File Specified\n" 2>&1 && exit
fileList=("$@")
lenFL=${#fileList[@]}

for (( i=0; i<"$lenFL"; i++ )); do
    printf "%s %s %s %s %s %s" "Resizing" "${fileList[$i]}" "to" "$(printf "%s" "$aspect" | awk '{print $2}')" "size and storing it at" "$outputDIR/${fileList[$i]}"
    convert -coalesce $aspect -gravity center -background "rgba(0,0,0,0)" -compose copy $extent  "${fileList[$i]}" "$outputDIR/${fileList[$i]}"
    printf '\033[2K\033[0G'
done
