#!/bin/bash
[ "$1" == "-h" -o "$1" == "--help" -o "$1" == "help" ] && printf "Usage: resize-image <OutputDir> [Size] <Inputfile>\nResize images and gifs at reasonable quality\n\nSize format: #x# or #\nSize must be integer\n" && exit
[ -z "$1" ] && printf "No Directory Specified\n" 2>&1 && exit
[ "${1: -1}" == "/" ] && outputDIR=${1%?} || outputDIR=$1
shift

if [ ! -z "$(printf "%s\n" "$1" | grep "[0-9]*" | grep "$(file --mime-type -- $1 | grep " image/.*" )" )" ]; then
    if [ -z "$1" ]; then
        aspect=""
        extent=""
    elif [ ! -z "$(printf "%s\n" "$1" | grep -o -i "x")" ]; then
        aspect="-scale $1"
        extent="-extent $1"
    else
        aspect="-scale $1x$1"
        extent="-extent $1x$1"
    fi
else
    printf "Invalid size!\n" 2>&1
    exit
fi

shift
[ -z "$1" ] && printf "No Input File Specified\n" 2>&1 && exit
fileList=($@)
lenFL=${#fileList[@]}

for (( i=0; i<$lenFL; i++ )); do
    printf "\r\033[2KResizing ${fileList[$i]} to $(printf "%s" "$aspect" | awk '{print $2}') size and storing it at $outputDIR/${fileList[$i]}\033[0G"
    convert -coalesce $aspect -gravity center -background "rgba(0,0,0,0)" -compose copy $extent  ${fileList[$i]} "$outputDIR/${fileList[$i]}"
done
printf "\n"
