#!/bin/bash

selection=$(slop -f "-i %i -g %g")
filename="$(date +%y%m%d%H%M%S).png"
case $1 in
    -s) shotgun $selection ~/Pictures/$filename;;
    -c) shotgun $selection - | xclip -t 'image/png' -selection clipboard
        shotgun $selction ~/Pictures/$filename
        ;;
    *) shotgun $selection - | xclip -t 'image/png' -selection clipboard;;
esac
