#!/bin/bash
[ -z "$1" ] && printf "Missing file\n" 2>&1 && exit
sound=$(printf "%s" "$1" | grep -o "\[sound=.*\]" | sed -e 's/\[sound=//g' -e 's/\]//g' -e 's/%3A/\:/g' -e 's/%2F/\//g')
if [ -z "$(printf "%s" \"$sound\" | grep -E 'https|http')" -a ! -z "$sound" ]; then
    soundlink=" -i https://$sound"
    map="-map 0:v:0 -map 1:a:0"
elif [ ! -z "$sound" ]; then
    soundlink=" -i $sound"
fi
#ffmpeg -i "$1" $soundlink -pix_fmt yuv420p -deinterlace -vf "scale=640:360" -vsync 1 -max_interleave_delta 0 -vcodec libx264 -r 29.970 -threads 0 -b:v: 1024k -bufsize 1216k -maxrate 1280k -preset medium -profile:v main -tune film -g 60 -x264opts no-scenecut -acodec aac -b:a 192k -ac 2 -ar 44100 -af "aresample=async=1:min_hard_comp=0.100000:first_pts=0" $map -f matroska -y pipe:1 | ffplay - -framedrop -infbuf 
ffmpeg -probesize 20M -i "$1" $soundlink -c:v libx264 -tune stillimage $map -max_interleave_delta 0 -fflags nobuffer -r 29.970 -g 100 -f matroska pipe:1 | ffplay - -framedrop -infbuf
