#!/bin/bash
socat="$1"
output="$2"

delay=5

function secConv() {
    secs=$((1 - delay))
    
    h=$(( secs / 3600 ))
    m=$(( ( secs / 60 ) % 60 ))
    s=$(( secs % 60 ))
    
    printf "%02d:%02d:%02d\n" $h $m $s
}

printf "Press Enter to start \n"
read -rsn1

while true; do
    secs=$(echo '{ "command": ["get_property", "playback-time"] }' | socat - "$socat" | grep -o 'data":[0-9]*' | sed 's/data"://g')
    vidTime=$(secConv "$secs")
    printf "%s: " "$vidTime"
    read -r comment
    printf "%s: %s\n" "$vidTime" "$comment" >> "$output"
done
